# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{monkeysupport}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Burke Libbey"]
  s.date = %q{2009-12-28}
  s.description = %q{MonkeySupport monkeypatches some of the performance-sink parts of rails with speedy C extensions.}
  s.email = %q{burke@burkelibbey.org}
  s.extensions = ["ext/monkeysupport_c/extconf.rb", "ext/monkeysupport_output_safety/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "ext/monkeysupport_c/extconf.rb",
     "ext/monkeysupport_c/src/activesupport_inflector.c",
     "ext/monkeysupport_c/src/activesupport_inflector.h",
     "ext/monkeysupport_c/src/monkeysupport_c.c",
     "ext/monkeysupport_output_safety/Makefile",
     "ext/monkeysupport_output_safety/extconf.rb",
     "ext/monkeysupport_output_safety/src/monkeysupport_output_safety.c",
     "lib/monkeysupport.rb",
     "lib/monkeysupport/activesupport/inflector.rb",
     "lib/monkeysupport/c_proxy.rb",
     "lib/monkeysupport/lru_cache.rb",
     "lib/monkeysupport/memoizable.rb",
     "monkeysupport.gemspec",
     "spec/output_safety_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/burke/monkeysupport}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Monkeypatching Rails with C since 2009}
  s.test_files = [
    "spec/output_safety_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

