# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{monkeysupport}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Burke Libbey"]
  s.date = %q{2009-09-04}
  s.description = %q{MonkeySupport provides C implementations for some of the more intensive string manipulation methods in activesupport. ActionView is up next.}
  s.email = %q{burke@burkelibbey.org}
  s.extensions = ["ext/monkeysupport_c/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/monkeysupport_c/extconf.rb",
     "ext/monkeysupport_c/extconf.rb",
     "ext/monkeysupport_c/src/activesupport_inflector.c",
     "ext/monkeysupport_c/src/activesupport_inflector.c",
     "ext/monkeysupport_c/src/activesupport_inflector.h",
     "ext/monkeysupport_c/src/activesupport_inflector.h",
     "ext/monkeysupport_c/src/monkeysupport_c.c",
     "ext/monkeysupport_c/src/monkeysupport_c.c",
     "lib/monkeysupport.rb",
     "lib/monkeysupport.rb",
     "lib/monkeysupport/activesupport/inflector.rb",
     "lib/monkeysupport/activesupport/inflector.rb",
     "lib/monkeysupport/c_proxy.rb",
     "lib/monkeysupport/c_proxy.rb",
     "lib/monkeysupport/memoizable.rb",
     "lib/monkeysupport/memoizable.rb",
     "lib/monkeysupport/type_checks.rb",
     "lib/monkeysupport/type_checks.rb",
     "monkeysupport.gemspec",
     "test/monkeysupport_test.rb",
     "test/monkeysupport_test.rb",
     "test/test_helper.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/burke/monkeysupport}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Monkeypatching Rails with C since 2009}
  s.test_files = [
    "test/monkeysupport_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
